<a href="https://colab.research.google.com/github/mintra-tippayaratsontorn/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np  # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ Matrix)

# Numpy Array

## สร้าง Numpy array(matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

# Matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

สร้าง Matrix เริ่มต้น (zeros,ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_0 = np.ones((5,6))
np_0

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [10]:
np.random.randn(5,5)  #random มาจากเลข normal distribution ที่มี mu = 0 std=1

array([[ 0.35916132,  1.09023953,  0.04631869, -2.30736143, -1.00617234],
       [-0.75223838,  1.26890744, -0.48801126,  1.87851767, -1.53575558],
       [-1.262623  ,  0.28084953,  0.99112234,  0.03570672,  0.81815894],
       [-0.06941651, -0.64254762,  0.76364071,  0.12301037,  1.29109342],
       [-0.74499085, -0.96257376, -2.73731681, -0.8313091 ,  0.42067478]])

In [11]:
2+(5*np.random.randn(3,3))

array([[ 3.67607665,  4.53610614,  8.58948813],
       [-1.56205084,  1.19159346,  1.01118521],
       [-1.8984529 ,  1.14132633, -1.71896677]])

In [12]:
np.random.randint(5,11,(4,5))  #random เลขจำนวนเต็ม ระหว่าง (5,11)  ขนาด (4x5)

array([[ 5,  6,  6,  5,  7],
       [ 9,  8,  7,  6,  6],
       [ 7,  9, 10,  9, 10],
       [ 7,  8,  7,  9,  9]])